// <auto-generated />
using BuilderCompany.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuilderCompany.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("BuilderCompany.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearCompleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Елітний житловий комплекс біля моря.",
                            ImageUrl = "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=500",
                            Location = "м. Одеса",
                            Name = "ЖК 'Морський'",
                            YearCompleted = 2023
                        },
                        new
                        {
                            Id = 2,
                            Description = "Екологічний будинок в лісовій зоні.",
                            ImageUrl = "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=500",
                            Location = "Одеська область",
                            Name = "Котедж 'Лісовий'",
                            YearCompleted = 2024
                        });
                });

            modelBuilder.Entity("BuilderCompany.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Будуємо сучасні та надійні будинки під ключ.",
                            IconClass = "🏠",
                            Title = "Будівництво котеджів"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Виконуємо всі види внутрішніх оздоблювальних робіт.",
                            IconClass = "🛠️",
                            Title = "Ремонт під ключ"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Створюємо індивідуальні архітектурні проекти.",
                            IconClass = "📐",
                            Title = "Проектування"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
